language: python
python:
  - 2.7
  - 3.5
  - 3.6
env:
  - DJANGO_VERSION='>=1.11,<2.0'
  - DJANGO_VERSION='>=2.0,<2.1'
  - DJANGO_VERSION='>=2.1,<2.2'
matrix:
  exclude:
    - python: 2.7
      env: DJANGO_VERSION='>=2.0,<2.1'
    - python: 2.7
      env: DJANGO_VERSION='>=2.1,<2.2'
# command to run tests
install: ./install_redis.sh
script: make test DJANGO_VERSION=$DJANGO_VERSION
branches:
  only:
    - unstable
    - master
